#include <stdio.h>
#include <immintrin.h> // Include AVX intrinsics header

// Code generated by Gemini... :(
int main() {
    // Example: Adding two arrays of 8 floats using AVX
    float a[8] = {1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f};
    float b[8] = {8.0f, 7.0f, 6.0f, 5.0f, 4.0f, 3.0f, 2.0f, 1.0f};
    float result[8];

    // Load arrays into YMM registers
    __m256 ymm_a = _mm256_loadu_ps(a); // load unaligned packed single-precision floating-point values.
    __m256 ymm_b = _mm256_loadu_ps(b);

    // Perform the addition using AVX
    __m256 ymm_result = _mm256_add_ps(ymm_a, ymm_b);

    // Store the result back to the array
    _mm256_storeu_ps(result, ymm_result);

    // Print the result
    printf("AVX Addition Result:\n");
    for (int i = 0; i < 8; i++) {
        printf("%.2f ", result[i]);
    }
    printf("\n");

    return 0;
}