#include <stdio.h>
#include <omp.h>

// Code generated by Gemini... :(
int main() {
    int thread_id, num_threads;

    // Get the number of threads available
    #pragma omp parallel
    {
        #pragma omp single
        {
            num_threads = omp_get_num_threads();
            printf("Number of threads: %d\n", num_threads);
        }
    }

    // Parallel region with thread ID printing
    #pragma omp parallel private(thread_id)
    {
        thread_id = omp_get_thread_num();
        printf("Hello from thread %d\n", thread_id);
    }

    //Example of a parallel for loop
    int array[10];

    #pragma omp parallel for
    for (int i = 0; i < 10; i++) {
        array[i] = i * 2;
        printf("Thread %d calculated array[%d] = %d\n", omp_get_thread_num(), i, array[i]);
    }

    return 0;
}